# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (attempt 1)
        id: checkout1
        uses: actions/checkout@v4
        continue-on-error: true
      - name: Checkout (attempt 2)
        id: checkout2
        if: steps.checkout1.outcome == 'failure'
        uses: actions/checkout@v4
        continue-on-error: true
      - name: Checkout (attempt 3)
        if: steps.checkout2.outcome == 'failure'
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check --output-format=github .

      - name: Ruff format check
        run: ruff format --check .

      - name: Typos check
        uses: crate-ci/typos@v1
